### PR TITLE
feat: react native integration builder

### PR DESCRIPTION
**Pull request by michaellee8**

### CODE REVIEW

**Comment by yashovardhan** [comment]
Errors are fixed, let's talk about this PR and missing things tomorrow.

**Comment by yashovardhan** [comment]
@michaellee8 any updates here?

**Comment by michaellee8** [comment]
> @michaellee8 any updates here?

Not yet

**Comment by michaellee8** [comment]
@yashovardhan The changed are made as u have asked, but there are a problem that I am unable to use different `package.json` for expo and bare modes. I will need your help to find out the proper way to rename those static files on the fly.

**Pull request merged**
