### PR TITLE
Fixing typos

### PR DESCRIPTION
**Pull request by eloi010**

### CODE REVIEW

**Comment by yashovardhan** [comment]
Hey @eloi010 

As I see it is not a typo. Thanks for your PR anyway. Closing this for now.

**Comment by eloi010** [comment]
verifer is not a typo?

**Comment by yashovardhan** [comment]
My apologies, I misread the changes somehow. The changes are valid.

Sorry for the confusion, thanks for your contribution!

**Review by yashovardhan — APPROVED** [review]
LGTM

**Pull request merged**
