### PR TITLE
Fix Integration Builder

### PR DESCRIPTION
**Pull request by yashovardhan**
This fixes starkex integration builder for react

todo: custom authentication, custom ui

### CODE REVIEW

**Comment by himanshuchawla009** [comment]
Screenshot 2022-06-07 at 7 26 34 AM

getting this error while running this branch.

**Comment by yashovardhan** [comment]
@himanshuchawla009 I'm not sure about this error.. I guess you might like to delete the previous metadata files and rebuild again?

**Comment by himanshuchawla009** [comment]
> @himanshuchawla009 I'm not sure about this error.. I guess you might like to delete the previous metadata files and rebuild again?

I deleted everything and cloned it again.

**Comment by himanshuchawla009** [comment]
Screenshot 2022-06-07 at 9 24 44 AM

Commented out rpc target should show mainnet rpc as chainId belongs to mainnet. Do the same for every example.

**Comment by himanshuchawla009** [comment]
Screenshot 2022-06-07 at 9 28 19 AM

The key shoud be replaced with "app scoped private key"

**Comment by himanshuchawla009** [comment]
Screenshot 2022-06-07 at 9 30 00 AM

cdn links are incorrect.

**Comment by himanshuchawla009** [comment]
Screenshot 2022-06-07 at 9 33 12 AM

remove "currently"

**Comment by himanshuchawla009** [comment]
Screenshot 2022-06-07 at 9 33 59 AM

there is not getPrivateKey function in provider.

**Comment by himanshuchawla009** [comment]
Screenshot 2022-06-07 at 9 34 36 AM

eth_private_key function is not available with other chainnamespace so it is incorrect.

**Comment by himanshuchawla009** [comment]
Screenshot 2022-06-07 at 9 35 59 AM

incorrect description, we are not taking any account index in the corresponding getAccount function.

**Comment by himanshuchawla009** [comment]
Screenshot 2022-06-07 at 9 41 21 AM

with webpack version >=5

**Comment by yashovardhan** [comment]
> Screenshot 2022-06-07 at 9 33 59 AM
> 
> there is not getPrivateKey function in provider.

where the getPrivateKey function reside then?

**Comment by yashovardhan** [comment]
> Screenshot 2022-06-07 at 9 35 59 AM
> 
> incorrect description, we are not taking any account index in the corresponding getAccount function.

can you tell me a better description for this?

**Comment by yashovardhan** [comment]
> Screenshot 2022-06-07 at 9 34 36 AM
> 
> eth_private_key function is not available with other chainnamespace so it is incorrect.

what should be the correct code here?

**Comment by himanshuchawla009** [comment]
> 

it doesn't exist, it is not even in your code snippet.

**Comment by himanshuchawla009** [comment]
> > Screenshot 2022-06-07 at 9 34 36 AM
> > eth_private_key function is not available with other chainnamespace so it is incorrect.
> 
> what should be the correct code here?

plz consult with lionell or swarak

**Comment by himanshuchawla009** [comment]
in custom Auth examples use @web3auth/core package if you are calling connectTo functions.

**Comment by himanshuchawla009** [comment]
> > Screenshot 2022-06-07 at 9 34 36 AM
> > eth_private_key function is not available with other chainnamespace so it is incorrect.
> 
> what should be the correct code here?

https://docs.web3auth.io/api-reference/web/providers/#other

**Comment by yashovardhan** [comment]
@himanshuchawla009 the requested changes are done

**Comment by yashovardhan** [comment]
Rebased the branch

**Comment by himanshuchawla009** [comment]
Screenshot 2022-06-07 at 4 32 09 PM

classname should be starknetRpc

**Comment by himanshuchawla009** [comment]
Screenshot 2022-06-07 at 4 35 26 PM

i don't think that this getAccounts function will work with other chainNameSpace. Plz confirm and remove it if it doesn't work.

**Comment by himanshuchawla009** [comment]
Screenshot 2022-06-07 at 4 38 57 PM

have you tested this , connect code snippet, i don' think it will works as intentional?

**Comment by himanshuchawla009** [comment]
> > Screenshot 2022-06-07 at 4 38 57 PM
> > have you tested this , connect code snippet, i don' think it works as intentional?
> 
> I tested with `connectTo` in `@web3auth/web3auth`, it was working fine. Changed to `connect` as you requested.

connect will work with custom auth but only with logins which are available in modal for ex: google, fb etc, it won't work with jwt login type which is being demostrated in docs.

**Comment by yashovardhan** [comment]
> Screenshot 2022-06-07 at 4 35 26 PM
> 
> i don't think that this getAccounts function will work with other chainNameSpace in starknet. Plz confirm and remove it if it doesn't work.

I have revamped both starkex and starknet files again according to new module imports you suggested yesterday. It works now. This function is removed.

**Comment by yashovardhan** [comment]
@himanshuchawla009 I've done the requested changes

**Review by himanshuchawla009 — APPROVED** [review]
Lgtm

**Pull request merged**
