### PR TITLE
Android Doc Update

### PR DESCRIPTION
**Pull request by shahbaz17**

### CODE REVIEW

**Review by yashovardhan — COMMENTED** [review]
Generally looks good, we should go through it together once tomorrow before merging. Let's do this for all major SDK Reference changes

**Comment by shahbaz17** [comment]
@yashovardhan 

Waiting for the dappShare general introduction. 

For now, I have added `mfaLevel`, `dappShare` and `curve` to usage as it is part of the `LoginParam` and has the interface and table defined on the same page. Later, if we want, we can branch off to a new page with more detailed information about each and in-depth examples.

**Comment by yashovardhan** [comment]
can you add a Multi Factor Authentication page as we discussed? We will be adding to all the SDK references. I'll add for web as well.

**Comment by shahbaz17** [comment]
Sure, making that change for this PR.

**Comment by shahbaz17** [comment]
@yashovardhan 

It's ready from my end. Can you review it once?

**Review by yashovardhan — APPROVED** [review]
Lgtm

**Pull request merged**
