### PR TITLE
CSS Improvements and Theme Changes

### PR DESCRIPTION
**Pull request by yashovardhan**
- Create Custom Theme for CodeView
- Filters on Guides
- New Banner

- Fix footer: still couldn't do it, cannot understand the root cause of the problem

### CODE REVIEW

**Comment by yashovardhan** [comment]
@lionellbriones I need your help here in fixing the footer.

**Review by shahbaz17 — APPROVED** [review]
Overall looks good to me. Nice work with `npm2yarn`.

For Guides search, sometimes, after the search, when you delete the word, it doesn’t roll back to its original state. Can you look into that? Or is it just for me?

**Comment by yashovardhan** [comment]
Fixed a few css issues with the guides. I spent quite some time figuring out the search issue. Since I'm not using any external library and directly using React's `onChange` function, the backspaces are not counted. Even after using some other function like `onKeyPress`/ `onKeyUp` there wasn't a way to update the state.

The only other way it seems is to maybe clear the bar on backspace or delete or let it be as it is.

**Comment by shahbaz17** [comment]
Guides search and footer theme is fixed.

Thanks @lionellbriones

**Comment by yashovardhan** [comment]
I'm adding highlights in search. Will merge after that.

**Comment by yashovardhan** [comment]
added highlights and did some fixes in code structure. I think this is ready to be merged.

**Pull request merged**
