### PR TITLE
solana wallet plugin docs fixed

### PR DESCRIPTION
**Pull request by himanshuchawla009**

### CODE REVIEW

**Comment by yashovardhan** [comment]
@himanshuchawla009 I think the `whiteLabel` parameter is not supported on Solana plugin

**Comment by himanshuchawla009** [comment]
> @himanshuchawla009 I think the `whiteLabel` parameter is not supported on Solana plugin

thats why i removed it right

**Comment by yashovardhan** [comment]
I will verify the rest of the parameters and fix it before merging

**Comment by himanshuchawla009** [comment]
> I will verify the rest of the parameters and fix it before merging

I have added only 2 params in docs, and 2 of them are working.

**Pull request merged**
