### PR TITLE
Add new Integration Builder highlighting technique

### PR DESCRIPTION
**Pull request by yashovardhan**
Fixes Integration Builder highlighting properly with a new scalable technique as recommended earlier by Himanshu.

Only implemented for Android currently for testing purposes. If the code looks fine, we will add it to other frameworks as well.

### CODE REVIEW

**Review by shahbaz17 — APPROVED** [review]
LGTM.

Normal and after toggle scenario works pretty well. Amazing work @yashovardhan 👏 

Note: This is only added for Android Integration builder only.

**Comment by yashovardhan** [comment]
The new highlighting technique is fixed, alongside the url copying as well. It is working fine on my local.

**Comment by yashovardhan** [comment]
fix url params

**Comment by yashovardhan** [comment]
fixed

**Pull request merged**
