### PR TITLE
Web3Auth Core Guides

### PR DESCRIPTION
**Pull request by shahbaz17**
* Google
* Facebook
* Discord
* Twitch

### CODE REVIEW

**Review by yashovardhan — CHANGES_REQUESTED** [review]
The discord logo seems old, we should change it

**Comment by shahbaz17** [comment]
Updated.

**Review by yashovardhan — APPROVED** [review]
I changed a few things around descriptions and tags. Let me know if that looks good to you. Otherwise everything else is ready to go

**Comment by shahbaz17** [comment]
Changes LGTM. 

Let's merge it.

**Pull request merged**
