### PR TITLE
Guides UI & typo fixes

### PR DESCRIPTION
**Pull request by shahbaz17**
* Changed guides banner
* Fixed typos

### CODE REVIEW

**Comment by yashovardhan** [comment]
@shahbaz17 I'm not sure if this is the guide image we finalised? It has the dots in there which I thought we were not moving forward with. A plain background looked better right?

**Comment by yashovardhan** [comment]
Also I just reviewed your cognito guide, there are a few changes we need to discuss.

**Comment by shahbaz17** [comment]
> @shahbaz17 I'm not sure if this is the guide image we finalised? It has the dots in there which I thought we were not moving forward with. A plain background looked better right?

Vinay is working on a new design. Will update the banner, once ready.

**Comment by shahbaz17** [comment]
> also since these are semi transparent, it looks weird when we toggle between dark and light modes

I have received this file from the Design team. Can you look into this design since you already worked on the Auth0 guide.

**Comment by yashovardhan** [comment]
I've fixed issues further. Also made the guides more consistent across. 

I noticed that we have not documented the cognito authorization code flow, are we not going to do that?

**Comment by yashovardhan** [comment]
Can we destructure the meta tags to reference the guide description/ title/ image etc?

**Pull request merged**
