### PR TITLE
Guide for no modal multichain connection

### PR DESCRIPTION
**Pull request by rtomas**
Not yet added to the blog.

Firsts this example PR must be merged : https://github.com/Web3Auth/web3auth-pnp-examples/pull/855

### CODE REVIEW

**Comment by rtomas** [comment]
@yashovardhan can't see in Vercel why is not deploying. locally is working ok. Can you send me the error ?

**Review by yashovardhan — CHANGES_REQUESTED** [review]
Please rebase and fix merge conflicts

**Comment by yashovardhan** [comment]
Try building locally, not just dev server mode. You should get the error.

**Comment by fauziyasin** [comment]
Done

**Comment by rtomas** [comment]
before approve, I need this image for the guide 
https://web3auth.io/docs/guides/banners/multichain.png

**Pull request closed without merging**
