### PR TITLE
Android Integration Builder Update

### PR DESCRIPTION
**Pull request by shahbaz17**

### CODE REVIEW

**Review by yashovardhan — CHANGES_REQUESTED** [review]
- Please check if the code works for each and every combination - this can become very critical when dynamically adding code
- Add steps for each toggle Custom Authentication, Whitelabel, MFA, dapp share - people should know that it exists when they enable the toggle.

- `val loginCompletableFuture: CompletableFuture<Web3AuthResponse> = web3Auth.login(LoginParams(selectedLoginProvider, mfaLevel = MFALevel.MANDATORY, dappShare = "<24 words seed phrase>"))`
  - This line is getting too big, please destructure into multiple lines
  - Please use a working code for dApp Share - the idea is that anyone using it can just copy paste and go. You can do it by adding a function that reads dapp share and stores into app local storage and finally passes that. This is long function, but that will only make sense for the integration builder.
- You have destructured multiple steps without headers - I get the idea of sub steps but I think for a better UX some kind of header is important. Please add some sub headering there.


Please work on these, in the meantime I will try to run the code in my system and check everything once.

**Comment by shahbaz17** [comment]
> * Please check if the code works for each and every combination - this can become very critical when dynamically adding code

Adjusted with working code, included `activity_main.xml` file for easier integration.

> * Add steps for each toggle Custom Authentication, Whitelabel, MFA, dapp share - people should know that it exists when they enable the toggle.

Steps added for each toggle along with the working code. Highlight is working for MFA and dApp Share. And for Custom AuthN and Whitelabel, it's generic highlight.

> * `val loginCompletableFuture: CompletableFuture<Web3AuthResponse> = web3Auth.login(LoginParams(selectedLoginProvider, mfaLevel = MFALevel.MANDATORY, dappShare = "<24 words seed phrase>"))`   
>   * This line is getting too big, please destructure into multiple lines

When destructured, it would break during build. If the idea is to copy and paste and have a working code. Then I recommend sticking with this structure.

>   * Please use a working code for dApp Share - the idea is that anyone using it can just copy paste and go. You can do it by adding a function that reads dapp share and stores into app local storage and finally passes that. This is long function, but that will only make sense for the integration builder.

dApp share is working and has a working code.

> * You have destructured multiple steps without headers - I get the idea of sub steps but I think for a better UX some kind of header is important. Please add some sub headering there.

Added.

> Please work on these, in the meantime I will try to run the code in my system and check everything once.

Did you had the chance to test the app?

**Review by yashovardhan — CHANGES_REQUESTED** [review]
The highlighting is a bit off.. please only highlight the sections that have to be added. For eg: Whitelabeling should only highlight whitelabel parameter in web3auth options. Custom Auth should only highlight loginConfig parameter


Destructure this line:

```
        val loginCompletableFuture: CompletableFuture<Web3AuthResponse> = web3Auth.login(LoginParams(selectedLoginProvider, mfaLevel = MFALevel.MANDATORY, dappShare = "afford join neutral spoon bike glue ahead floor giant match primary style cycle front address gossip embark rose boy muscle tuition melt left question"))

```

into multiple lines and only highlight the dapp share and mfa portions.


Finally, since you've hard coded dApp share, I think it will not work for anyone trying the app. dApp share changes for different people. 

You should add an if else statement - on first login dapp share is not passed, on consective logins, dapp share is passed from the app local storage

**Comment by yashovardhan** [comment]
`When destructured, it would break during build. If the idea is to copy and paste and have a working code. Then I recommend sticking with this structure.`
Oh sorry didn't see that, but I feel it should not break, how is the `Web3AuthOptions` destructured and working and `login` destructured and not working?

**Comment by yashovardhan** [comment]
> Did you had the chance to test the app?

Unfortunately no, android studio is not set up until now. I will do that later this week

**Comment by yashovardhan** [comment]
Let's remove dapp share from here.

**Comment by shahbaz17** [comment]
Removed dapp Share.

Please check the code highlighting while testing. Rest looks good to merge.

**Review by yashovardhan — APPROVED** [review]
Fixed the highlighting issues, LGTM

**Comment by shahbaz17** [comment]
Highlighting looks odd, without any toggle of custom auth, mfa and whitelabel.

**Comment by yashovardhan** [comment]
Oh I didn't check it without the toggles. I'll fix it.

**Pull request merged**
